engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - coffeescript
      - ruby  
ratings:
  paths:
  - "source/playbook.js"
  - "source/navigation.js"
  - "source/layouts/layout.erb"
  - "source/stylesheets/playbook.css"  
exclude_paths:
- "source/**/*"  
