engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - coffeescript  
ratings:
  paths:
  - src/**
  - "**.js"
  - "**.coffee"  
exclude_paths:
- "source/**/*"  
